version: '3'
services:
  mongo:
    image: mongo:4
    command: mongod --port 27020
    ports:
        - "27020:27020"
  web:
    build: .
    ports:
        - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27020/matcha
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/matcha
     - /matcha/node_modules

